apiVersion: v1
kind: Service
metadata:
  name: psr-diversity-site-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: psr-diversity-site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psr-diversity-site
  labels:
    app: psr-diversity-site
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psr-diversity-site
  template:
    metadata:
      labels:
        app: psr-diversity-site
    spec:
      containers:
      - name: psr-diversity-site
        image: corvimae/psr-diversity-site:latest
        ports:
        - containerPort: 3000